In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
# Load and process the dataset
df = pd.read_csv("Crop_Recom_Dataset.csv")

# Define input and target
Input = df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]
Target = df[['label']]

In [10]:
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

In [11]:
# Scale input features
scaler = MinMaxScaler()
Input = scaler.fit_transform(Input)
#Input = pd.DataFrame(Input, columns=['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'])
Input

array([[0.64285714, 0.26428571, 0.19      , ..., 0.79026683, 0.46626364,
        0.65645778],
       [0.60714286, 0.37857143, 0.18      , ..., 0.77063285, 0.54948026,
        0.74167459],
       [0.42857143, 0.35714286, 0.195     , ..., 0.79397664, 0.67421877,
        0.87571039],
       ...,
       [0.84285714, 0.2       , 0.125     , ..., 0.61788046, 0.44443315,
        0.55007079],
       [0.83571429, 0.19285714, 0.145     , ..., 0.44175991, 0.50604494,
        0.38428046],
       [0.74285714, 0.09285714, 0.125     , ..., 0.53822177, 0.50931694,
        0.43372112]])

In [13]:
# Encoder input features
Encoder = OneHotEncoder(sparse_output=False)
Output = Encoder.fit_transform(Target)
Output[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0.])

In [16]:
# Split data into test and train
x_train, x_test, y_train, y_test = train_test_split(Input, Output, test_size=0.3, random_state=42)

# Print shapes for verification
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1540, 7) (1540, 22)
(660, 7) (660, 22)


In [18]:
x_test[0]

# x_train

y_test[0]

# y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0.])

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

In [21]:
# Clear any previous model or variable names
model = Sequential()
model.add(Input(shape=(7,)))                    # Use Input layer to define shape
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=22, activation='softmax'))  # Output layer for 22 classes


model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           1,024 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 22)                  │             726 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 12,086 (47.21 KB)

 Trainable params: 12,086 (47.21 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [23]:
# Train the model
history = model.fit(x_train, y_train, epochs=25,
                    batch_size=32,
                    validation_data=(x_test, y_test))

Epoch 1/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.1090 - loss: 3.0577 - val_accuracy: 0.2030 - val_loss: 2.8877
Epoch 2/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2351 - loss: 2.7756 - val_accuracy: 0.2848 - val_loss: 2.3212
Epoch 3/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3812 - loss: 2.1388 - val_accuracy: 0.5258 - val_loss: 1.6085
Epoch 4/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6133 - loss: 1.4049 - val_accuracy: 0.6909 - val_loss: 1.0628
Epoch 5/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7381 - loss: 0.9615 - val_accuracy: 0.7955 - val_loss: 0.7992
Epoch 6/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8153 - loss: 0.7213 - val_accuracy: 0.8197 - val_loss: 0.6442
Epoch 7/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8271 - loss: 0.5970 - val_accuracy: 0.8667 - val_loss: 0.5450
Epoch 8/25
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8760 - loss: 0.4855 - val_accuracy: 0.8818 - val_los

In [32]:
model.evaluate(x_test,y_test)

21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9447 - loss: 0.1466


[0.12654605507850647, 0.9575757384300232]

In [34]:
# Predict on test data
y_pred = model.predict(x_test)

# Convert one-hot encoded predictions and labels back to class labels
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

from sklearn.metrics import classification_report
report = classification_report(y_test_classes, y_pred_classes, target_names=Encoder.categories_[0])
print(report)

21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        34
      banana       1.00      1.00      1.00        26
   blackgram       0.89      0.92      0.91        26
    chickpea       1.00      1.00      1.00        34
     coconut       1.00      1.00      1.00        33
      coffee       0.97      0.97      0.97        30
      cotton       0.93      1.00      0.97        28
      grapes       1.00      1.00      1.00        23
        jute       0.86      0.74      0.79        34
 kidneybeans       0.97      1.00      0.99        36
      lentil       0.81      0.95      0.88        22
       maize       1.00      0.92      0.96        26
       mango       0.94      1.00      0.97        32
   mothbeans       0.97      0.88      0.92        34
    mungbean       1.00      1.00      1.00        30
   muskmelon       1.00      1.00      1.00        24
      orange       1.00      1.00      1.0

# Web APP

In [37]:
import joblib
# Save the scaler using joblib
joblib.dump(scaler, 'App/crop_recommendation_scaler.joblib')

# Save the entire model
model.save('App/crop_recommendation_model.keras')

In [39]:
# Save the entire model
model.save('App/crop_recommendation_model.h5')